export enum Permission {
  VER_OT = 'VER_OT',
  VER_TODAS_OT = 'VER_TODAS_OT',
  VER_TODAS_OT_LOCATIVO = 'VER_TODAS_OT_LOCATIVO',
  CREAR_OT_EQUIPO = 'CREAR_OT_EQUIPO',
  CREAR_OT_LOCATIVO = 'CREAR_OT_LOCATIVO',
  EDITAR_OT = 'EDITAR_OT',
  INICIAR_OT = 'INICIAR_OT',
  FINALIZAR_OT = 'FINALIZAR_OT',
  ASIGNAR_TECNICO = 'ASIGNAR_TECNICO',
  REASIGNAR_TECNICO = 'REASIGNAR_TECNICO',
  CAMBIAR_ACTIVO_OT = 'CAMBIAR_ACTIVO_OT',
  CAMBIAR_UBICACION_OT = 'CAMBIAR_UBICACION_OT',
  ANULAR_OT = 'ANULAR_OT',
  CERRAR_OT = 'CERRAR_OT',
  VER_ACTIVOS = 'VER_ACTIVOS',
  VER_HISTORIAL_ACTIVO = 'VER_HISTORIAL_ACTIVO',
  EDITAR_ACTIVOS = 'EDITAR_ACTIVOS',
  VER_EVENTOS = 'VER_EVENTOS',
  VER_BAJAS = 'VER_BAJAS',
  VER_TRASLADOS = 'VER_TRASLADOS',
  CREAR_TRASLADOS = 'CREAR_TRASLADOS',
  EDITAR_TRASLADOS = 'EDITAR_TRASLADOS',
  VER_CATEGORIAS_ACTIVOS = 'VER_CATEGORIAS_ACTIVOS',
  EDITAR_CATEGORIAS_ACTIVOS = 'EDITAR_CATEGORIAS_ACTIVOS',
  VER_CATEGORIAS_LOCATIVOS = 'VER_CATEGORIAS_LOCATIVOS',
  EDITAR_CATEGORIAS_LOCATIVOS = 'EDITAR_CATEGORIAS_LOCATIVOS',
  VER_UBICACIONES = 'VER_UBICACIONES',
  EDITAR_UBICACIONES = 'EDITAR_UBICACIONES',
  GENERAR_REPORTES = 'GENERAR_REPORTES',
  VER_DASHBOARD = 'VER_DASHBOARD',
  CREAR_USUARIOS = 'CREAR_USUARIOS',
  CAMBIAR_PASSWORD_USUARIO = 'CAMBIAR_PASSWORD_USUARIO',
  VER_ALMACEN = 'VER_ALMACEN',
  VER_TODOS_ALMACENES = 'VER_TODOS_ALMACENES',
  VER_ITEMS_ALMACEN = 'VER_ITEMS_ALMACEN',
  VER_MOVIMIENTOS_ALMACEN = 'VER_MOVIMIENTOS_ALMACEN',
  VER_ALERTAS_ALMACEN = 'VER_ALERTAS_ALMACEN',
  EDITAR_ALMACEN = 'EDITAR_ALMACEN',
  EDITAR_ITEMS_ALMACEN = 'EDITAR_ITEMS_ALMACEN',
  INGRESAR_STOCK = 'INGRESAR_STOCK',
  VER_TRASLADOS_ALMACEN = 'VER_TRASLADOS_ALMACEN',
  CREAR_TRASLADOS_ALMACEN = 'CREAR_TRASLADOS_ALMACEN',
  VER_SOLICITUDES = 'VER_SOLICITUDES',
  VER_ORDENES_CERRADAS = 'VER_ORDENES_CERRADAS',
  EDITAR_SOLICITUD = 'EDITAR_SOLICITUD',
  CERRAR_SOLICITUD = 'CERRAR_SOLICITUD',
  RECHAZAR_SOLICITUD = 'RECHAZAR_SOLICITUD',
  EDITAR_OT_CERRADA = 'EDITAR_OT_CERRADA',
  VER_PERFILES = 'VER_PERFILES',
  CREAR_PERFILES = 'CREAR_PERFILES',
  EDITAR_PERFILES = 'EDITAR_PERFILES',
  VER_STOCK = 'VER_STOCK',
  EDITAR_STOCK = 'EDITAR_STOCK',
  CONSUMIR_ALMACEN_OT = 'CONSUMIR_ALMACEN_OT',
  EDITAR_CONSUMO_ALMACEN_OT = 'EDITAR_CONSUMO_ALMACEN_OT',
}

export const ALL_PERMISSIONS = Object.values(Permission);

export const PERMISSION_LABELS: Record<Permission, string> = {
  [Permission.VER_OT]: 'Ver órdenes de trabajo asignadas',
  [Permission.VER_TODAS_OT]: 'Ver todas las OT de equipo',
  [Permission.VER_TODAS_OT_LOCATIVO]: 'Ver todas las OT locativas',
  [Permission.CREAR_OT_EQUIPO]: 'Crear OT de equipo',
  [Permission.CREAR_OT_LOCATIVO]: 'Crear OT locativo',
  [Permission.EDITAR_OT]: 'Editar órdenes de trabajo',
  [Permission.INICIAR_OT]: 'Iniciar orden de trabajo',
  [Permission.FINALIZAR_OT]: 'Finalizar orden de trabajo',
  [Permission.ASIGNAR_TECNICO]: 'Asignar técnico',
  [Permission.REASIGNAR_TECNICO]: 'Reasignar técnico/contratista',
  [Permission.CAMBIAR_ACTIVO_OT]: 'Cambiar activo de la OT',
  [Permission.CAMBIAR_UBICACION_OT]: 'Cambiar ubicación de la OT',
  [Permission.ANULAR_OT]: 'Anular órdenes de trabajo',
  [Permission.CERRAR_OT]: 'Cerrar órdenes de trabajo',
  [Permission.VER_ACTIVOS]: 'Ver activos',
  [Permission.VER_HISTORIAL_ACTIVO]: 'Ver historial del activo',
  [Permission.EDITAR_ACTIVOS]: 'Editar activos',
  [Permission.VER_EVENTOS]: 'Ver eventos',
  [Permission.VER_BAJAS]: 'Ver bajas',
  [Permission.VER_TRASLADOS]: 'Ver traslados',
  [Permission.CREAR_TRASLADOS]: 'Crear traslados',
  [Permission.EDITAR_TRASLADOS]: 'Editar traslados',
  [Permission.VER_CATEGORIAS_ACTIVOS]: 'Ver categorías de activos',
  [Permission.EDITAR_CATEGORIAS_ACTIVOS]: 'Editar categorías de activos',
  [Permission.VER_CATEGORIAS_LOCATIVOS]: 'Ver categorías locativas',
  [Permission.EDITAR_CATEGORIAS_LOCATIVOS]: 'Editar categorías locativas',
  [Permission.VER_UBICACIONES]: 'Ver ubicaciones',
  [Permission.EDITAR_UBICACIONES]: 'Editar ubicaciones',
  [Permission.GENERAR_REPORTES]: 'Generar reportes',
  [Permission.VER_DASHBOARD]: 'Ver dashboard',
  [Permission.CREAR_USUARIOS]: 'Crear usuarios',
  [Permission.CAMBIAR_PASSWORD_USUARIO]: 'Cambiar contraseña de usuario',
  [Permission.VER_ALMACEN]: 'Ver almacén e inventario',
  [Permission.VER_TODOS_ALMACENES]: 'Ver todos los almacenes',
  [Permission.VER_ITEMS_ALMACEN]: 'Ver items',
  [Permission.VER_MOVIMIENTOS_ALMACEN]: 'Ver movimientos (Kardex)',
  [Permission.VER_ALERTAS_ALMACEN]: 'Ver alertas de stock bajo',
  [Permission.EDITAR_ALMACEN]: 'Editar almacén',
  [Permission.EDITAR_ITEMS_ALMACEN]: 'Editar items de almacén',
  [Permission.INGRESAR_STOCK]: 'Ingresar stock',
  [Permission.VER_TRASLADOS_ALMACEN]: 'Ver traslados de almacén',
  [Permission.CREAR_TRASLADOS_ALMACEN]: 'Crear traslados de almacén',
  [Permission.VER_SOLICITUDES]: 'Ver módulo Solicitudes',
  [Permission.VER_ORDENES_CERRADAS]: 'Ver módulo Órdenes de Trabajo',
  [Permission.EDITAR_SOLICITUD]: 'Editar solicitudes',
  [Permission.CERRAR_SOLICITUD]: 'Cerrar solicitudes',
  [Permission.RECHAZAR_SOLICITUD]: 'Rechazar solicitudes',
  [Permission.EDITAR_OT_CERRADA]: 'Editar OT cerrada',
  [Permission.VER_PERFILES]: 'Ver perfiles',
  [Permission.CREAR_PERFILES]: 'Crear perfiles',
  [Permission.EDITAR_PERFILES]: 'Editar perfiles',
  [Permission.VER_STOCK]: 'Ver stock de almacén',
  [Permission.EDITAR_STOCK]: 'Editar stock de almacén',
  [Permission.CONSUMIR_ALMACEN_OT]: 'Registrar consumo de almacén en OT',
  [Permission.EDITAR_CONSUMO_ALMACEN_OT]: 'Editar consumo de almacén en OT cerrada',
};
